#server:
#  port: 8080

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/phoneBookDB
#    username: root
#    password: 1
  jpa:
    hibernate:
      ddl-auto: update


security:
  oauth2:
    resource:
      jwt:
        key-value: JWT-t0ken-Secret_Key

#---
#server:
#  port: ${PORT}